import { createApp } from 'vue';
import {
  create,
  NAlert,
  NAvatar,
  NButton,
  NCard,
  NCheckbox,
  NCheckboxGroup,
  NCode,
  NConfigProvider,
  NDataTable,
  NDescriptions,
  NDescriptionsItem,
  NDialogProvider,
  NDrawer,
  NDrawerContent,
  NEllipsis,
  NEmpty,
  NForm,
  NFormItem,
  NGi,
  NGrid,
  NH3,
  NIcon,
  NInput,
  NInputGroup,
  NLayout,
  NLayoutContent,
  NLayoutHeader,
  NLayoutSider,
  NList,
  NListItem,
  NLog,
  NMenu,
  NMessageProvider,
  NModal,
  NNotificationProvider,
  NPageHeader,
  NSelect,
  NSpace,
  NStatistic,
  NTabPane,
  NTabs,
  NTag,
  NText,
  NThing,
  NTimeline,
  NTimelineItem,
} from 'naive-ui';
import App from './app/App.vue';
import { createDashboardI18n } from './i18n';
import './styles/tokens.css';
import './styles/layout.css';
import './styles/components.css';

const naive = create({
  components: [
    NAlert,
    NAvatar,
    NButton,
    NCard,
    NCheckbox,
    NCheckboxGroup,
    NCode,
    NConfigProvider,
    NDataTable,
    NDescriptions,
    NDescriptionsItem,
    NDialogProvider,
    NDrawer,
    NDrawerContent,
    NEllipsis,
    NEmpty,
    NForm,
    NFormItem,
    NGi,
    NGrid,
    NH3,
    NIcon,
    NInput,
    NInputGroup,
    NLayout,
    NLayoutContent,
    NLayoutHeader,
    NLayoutSider,
    NList,
    NListItem,
    NLog,
    NMenu,
    NMessageProvider,
    NModal,
    NNotificationProvider,
    NPageHeader,
    NSelect,
    NSpace,
    NStatistic,
    NTabPane,
    NTabs,
    NTag,
    NText,
    NThing,
    NTimeline,
    NTimelineItem,
  ],
});

createApp(App).use(createDashboardI18n()).use(naive).mount('#app');
